title: Obsidian Nightfall
description: >-
  An elegante, dark Theme by Volkan Sah
baseurl: "/test_jelly" # Der Name Ihres Repositories
url: "https://volkansah.github.io" # Ihre GitHub Pages URL
theme: minima # Oder dein eigenes Theme, z.B. "obsidian-nightfall", falls entwickelt.
