title: Obsidian Nightfall
description: >-
  An elegante, dark Theme by Volkan Sah
baseurl: "" # Muss leer sein, wenn du GitHub Pages mit einem benutzerdefinierten Domainnamen nutzt.
url: "https://volkansah.github.io/" # Ersetze durch deine URL.
theme: minima # Oder dein eigenes Theme, z.B. "obsidian-nightfall", falls entwickelt.
