jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle

    - name: Build Jekyll site
      run: JEKYLL_ENV=production bundle exec jekyll build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
